version: '3'

services:
    app:
      build: 
        context: ./node
      container_name: node
      entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
      networks: 
        - node-network
      tty: true
      depends_on: 
         - db

    db:
      build:
        context: ./mysql
      command: --innodb-use-native-aio=0
      container_name: db
      restart: always
      tty: true
      volumes: 
        - ./mysql/data:/var/lib/mysql
      environment: 
        - MYSQL_DATABASE=challenge
        - MYSQL_ROOT_PASSWORD=root
      networks: 
        - node-network
        
    nginx:
      build: 
        context: ./nginx
      container_name: nginx
      networks: 
        - node-network
      ports: 
        - "8080:80"

networks: 
  node-network:
    driver: bridge